version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth_api
      - JWT_SECRET=supersecuresecret
      - JWT_EXPIRES_IN=1d
